# Generated by Django 2.2.6 on 2019-11-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(upload_to='imagens'),
        ),
    ]
