# Generated by Django 2.2.6 on 2019-11-22 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0004_auto_20191118_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='comprado',
            field=models.ManyToManyField(related_name='produtos', through='loja.ProdutoCliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
