# Generated by Django 2.2.6 on 2019-11-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20191122_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtocliente',
            options={'managed': True, 'verbose_name': 'ProdutoCliente', 'verbose_name_plural': 'ProdutoClientes'},
        ),
        migrations.AlterModelTable(
            name='produtocliente',
            table='',
        ),
    ]
