# Generated by Django 2.2.6 on 2019-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_auto_20191122_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'managed': True, 'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinho'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
