# Generated by Django 2.2.6 on 2019-11-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
