# Generated by Django 2.2.6 on 2019-11-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_auto_20191125_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto')),
            ],
            options={
                'verbose_name': 'ProdutoCarrinho',
                'verbose_name_plural': 'ProdutoCarrinhos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
